# Generated by Django 4.1 on 2022-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=127)),
                ('host', models.CharField(max_length=255)),
                ('full_path_info', models.TextField()),
                ('scheme', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('meta_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
